---
version: "2.1"

services:
  wireguard:
    image: ghcr.io/linuxserver/wireguard
    container_name: wireguard
    depends_on:
      - pihole
    dns:
      - ${VULTR_IP}
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Cayman
      - "SERVERURL=${VULTR_IP}"
      - "SERVERPORT=${WIREGUARD_PORT}"
      - PEERS=1, 3, 5 #optional
      - PEERDNS=auto #optional
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ~/wireguard/appdata/config:/config
      - /lib/modules:/lib/modules
    ports:
      # HOST:CONTAINER
      - ${WIREGUARD_PORT}:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  pihole:
    image: pihole/pihole:latest
    volumes:
      - ../../data/pi-hole/etc/:/etc/pihole/
      - ../../data/pi-hole/dnsmasq.d:/etc/dnsmasq.d
    environment:
      - TZ=America/Cayman
      - PROXY_LOCATION=pihole
      - VIRTUAL_HOST=${DOMAIN_NAME_1}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_EMAIL=${DEFAULT_EMAIL}
      - LETSENCRYPT_HOST=pihole.${DOMAIN_NAME_1}
    restart: unless-stopped
    networks:
      network-pihole:
        - ipv4_address=${VULTR_IP}

networks:
  network-pihole:
    name: "dns-pihole"
